module:
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  color: 0
  composer_manager: 0
  config: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  rest: 0
  s3fs: 0
  serialization: 0
  system: 0
  text: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  westminster: 1000
theme:
  classy: 0
  yorkshire: 0
  westminster_theme: 0
